### ISSUE TITLE
Branch naming is confusing

### ISSUE THREAD

**Issue by danielpanteleit** [mass-project/mass_client#1]
The default branch is MASS-165. Not sure what this means though. In the requirements for mass_system_ssdeep new_api is used, but this removes `FileAnalysisClient` for no obvious reason. Also master is deprecated. Why not use master as the default branch?

**Comment by fabian-marquardt** [comment]
There is some ongoing work due to migration to a new clientside codebase written by @Silberschleier 

@tbehner please make sure that the production-ready versions of mass_api_client, mass_client, etc. are merged to the master.

**Comment by tbehner** [comment]
Done.
